library(sqldf)
df <- read.csv.sql('household_power_consumption.txt',"select * from file where  Date in ('1/2/2007','2/2/2007')", sep = ';', header = T)
df$DateTime <- as.POSIXct(paste(df$Date, df$Time), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480, units = "px", bg =  "transparent")
plot(df$DateTime, df$Sub_metering_1, type="l", xlab="", ylab="Energy Sub  Metering")
lines(df$DateTime, df$Sub_metering_2, col="blue")
lines(df$DateTime, df$Sub_metering_3, col="red")
legend("topright", col = c("black", "blue", "red"), legend = c("Sub_metering_1",  "Sub_metering_2", "Sub_metering_3"), lwd=1)
dev.off()