library(sqldf)
df <- read.csv.sql('household_power_consumption.txt',"select * from file where  Date in ('1/2/2007','2/2/2007')", sep = ';', header = T)
png(filename = "plot1.png", width = 480, height = 480, units = "px", bg =  "transparent")
hist(as.numeric(df$Global_active_power), col="red", main="Global Active Power",  xlab="Global Active Power (kilowatts)")
dev.off()