library(sqldf)
df <- read.csv.sql('household_power_consumption.txt',"select * from file where  Date in ('1/2/2007','2/2/2007')", sep = ';', header = T)
df$DateTime <- as.POSIXct(paste(df$Date, df$Time), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot2.png", width = 480, height = 480, units = "px", bg =  "transparent")
plot(df$DateTime,df$Global_active_power, type="l", xlab="", ylab="Global Active  Power (kilowatts)")
dev.off()